const fs = require('fs');
const path = require('path');
const { marked } = require('marked');
const llm = require('../adapters/llm');
const vectorStore = require('../adapters/vector');
const { extractNpdsCode } = require('../config/npds-catalog');
const { rewriteImageLinks, buildFileIndex } = require('./imageLinks');

const MAX_CHUNK_LENGTH = 1500;
// 批次 embedding 每批筆數，降低 API 請求數與 429 風險
const EMBED_BATCH_SIZE = 100;

// .docx 等格式經 markitdown 轉檔時，若圖片沒有作者手寫的替代文字，Word 會自動產生
// alt-text 並固定帶一句免責聲明，markitdown 原樣保留進 Markdown。含多張圖的 chunk 因此
// 重複出現這句話多次，任何查詢命中這句話裡的詞（如「AI」）時 BM25 詞頻被純噪音灌高，
// 蓋過真正相關但圖少/沒圖的 chunk（實測案例：EAR-100T AI 運算效能那題）。
// 只移除這句固定字串本身，不影響圖片語法或 alt-text 裡其他描述文字。
function stripAutoGeneratedBoilerplate(text) {
  return String(text || '').replace(/\s*AI\s+產生的內容可能不正確[。.]?/g, '');
}

// ===== Sidecar 表格列抽取（不影響主 chunk 切塊）=====
// 密集規格/pin 表整張一個 chunk 時，單屬性查詢（重量、IP、pin1）對整表 embedding 相似度
// 被稀釋而召回不到（spec-table-recall-dilution）。前案「拆列進主池」經完整回歸證實淨負
// （碎片與正文無界競爭，見 openspec archive split-large-tables-into-rows [REJECTED]）。
// 此處改為 sidecar：整張表仍留在主 chunk，每列「另外」存進獨立 table_rows，只在檢索時
// 以相似度門檻限量注入候選池（retrieval.js）。列 title 帶章節路徑與表格 caption
// （如「Table 25: System specifications of MTi-680G」）——caption 是列的實體標籤，
// 沒有它，MTi 標準模組與 680G 的「Height」列無從分辨（跨實體混值）。
const MIN_TABLE_ROWS = 3; // body 列數超過此值才產 sidecar 列

// HTML <table> → [[表頭cells], [列cells], ...]
function htmlTableRows(html) {
  return [...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(tr =>
    [...tr[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)]
      .map(c => c[1].replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()));
}

// markdown pipe 表 token → [[表頭cells], [列cells], ...]
function mdTableRows(token) {
  const cell = c => (c && c.text != null ? c.text : String(c ?? '')).trim();
  return [(token.header || []).map(cell), ...(token.rows || []).map(r => r.map(cell))];
}

// token 是表格則回傳其列陣列（HTML 或 markdown），否則 null
function tableRowsOf(token) {
  if (token.type === 'table') return mdTableRows(token);
  if (token.type === 'html') {
    const m = String(token.raw || '').match(/<table[\s\S]*?<\/table>/i);
    if (m) return htmlTableRows(m[0]);
  }
  return null;
}

// 表格列陣列 → 每 body 列一筆 {title, text, firstCell}；列數不足門檻回 null（不產）。
// text = 表頭欄名 + 該列儲存格；firstCell 供檢索端字面加成（pin 表首格 = pin 編號）。
function tableRowChunks(rows, title) {
  if (!rows || rows.length < 2) return null;
  const header = rows[0].filter(Boolean).join(' | ');
  const body = rows.slice(1).filter(r => r.some(Boolean));
  if (body.length <= MIN_TABLE_ROWS) return null;
  return body.map(r => {
    const cells = r.filter(Boolean).join(' | ');
    return {
      title,
      text: header ? `${header} | ${cells}` : cells,
      firstCell: (r.find(Boolean) || '').trim(),
    };
  });
}

// 走一遍 token 流抽 sidecar 列：標題堆疊邏輯與 parseAndChunk 一致（含整段粗體標題），
// 另捕捉表格前最近的 caption 段落（markitdown 轉出的「Table N: ...」表標題）併進 title。
function extractTableRows(markdownText, filename) {
  const tokens = marked.lexer(stripAutoGeneratedBoilerplate(markdownText));
  const stack = [];
  const out = [];
  let lastCaption = '';
  const titleOf = () => (stack.length ? stack.map(h => h.text).join(' › ') : filename);
  const boldText = (token) => {
    if (token.type !== 'paragraph') return null;
    const m = String(token.raw || '').trim().match(/^\*\*([^\n]+?)\*\*$/);
    return m ? m[1].trim() : null;
  };
  for (const token of tokens) {
    const bold = boldText(token);
    if (token.type === 'heading' || bold) {
      const depth = bold ? 99 : token.depth;
      while (stack.length && stack[stack.length - 1].depth >= depth) stack.pop();
      stack.push({ depth, text: bold || token.text });
      lastCaption = '';
      continue;
    }
    // caption 判定：短段落且以「Table N.」/「Table N:」開頭
    if (token.type === 'paragraph') {
      const t = String(token.text || '').trim();
      lastCaption = (/^Table\s+[\d.-]+[.:]/i.test(t) && t.length < 120) ? t : '';
      continue;
    }
    const rows = tableRowChunks(tableRowsOf(token), titleOf());
    if (rows) {
      const cap = lastCaption ? ` › ${lastCaption}` : '';
      out.push(...rows.map(r => ({ ...r, title: `${r.title}${cap}` })));
    }
    if (token.type !== 'space') lastCaption = '';
  }
  return out;
}

function parseAndChunk(markdownText, filename) {
  const tokens = marked.lexer(stripAutoGeneratedBoilerplate(markdownText));
  const chunks = [];
  // 標題階層堆疊：title 為完整章節路徑（H1 › H2 › H3），深層小節才保得住脈絡，
  // 且路徑會參與 embedding/FTS 比對。無任何標題時 title 為檔名。
  const headingStack = [];
  let currentText = '';

  const currentTitle = () =>
    (headingStack.length ? headingStack.map(h => h.text).join(' › ') : filename);

  function flushChunk() {
    const text = currentText.trim();
    if (text) {
      const title = currentTitle();
      splitLongChunk(text, title).forEach(t => chunks.push({ title, text: t }));
    }
    currentText = '';
  }

  // 「整段皆為粗體」的段落當標題邊界：有些文件（如 FAQ）用 **Q1: ...** 粗體充當段落標題、
  // 完全沒有 # 標題，若不處理會被整份視為無標題、按長度硬切，多個不相關主題混進同一 chunk，
  // 單一主題查詢對這種多主題 chunk 召回被稀釋。深度給 BOLD_HEADING_DEPTH（比任何 # 都深），
  // 附加在現有 # 章節路徑之下、不覆蓋它。只認「整段粗體」，行內部分粗體不算。
  const BOLD_HEADING_DEPTH = 99;
  const boldHeadingText = (token) => {
    if (token.type !== 'paragraph') return null;
    const raw = String(token.raw || '').trim();
    const m = raw.match(/^\*\*([^\n]+?)\*\*$/); // 單行、整行以 ** 包裹
    return m ? m[1].trim() : null;
  };

  for (const token of tokens) {
    const boldTitle = boldHeadingText(token);
    if (token.type === 'heading' || boldTitle) {
      flushChunk();
      const depth = boldTitle ? BOLD_HEADING_DEPTH : token.depth;
      const text = boldTitle || token.text;
      // 同層或較淺的標題出現 → 截斷堆疊再壓入（跳層按實際 depth 放，不補洞）
      while (headingStack.length && headingStack[headingStack.length - 1].depth >= depth) {
        headingStack.pop();
      }
      headingStack.push({ depth, text });
    } else if (token.type === 'space') {
      currentText += '\n';
    } else if (token.raw) {
      currentText += token.raw;
    }
  }
  flushChunk();

  return chunks;
}

function splitLongChunk(text, title) {
  if (text.length <= MAX_CHUNK_LENGTH) return [text];

  const paragraphs = text.split(/\n+/).filter(p => p.trim());
  const result = [];
  let current = '';

  for (const para of paragraphs) {
    if (current.length + para.length + 2 > MAX_CHUNK_LENGTH && current.length > 0) {
      result.push(current.trim());
      current = para;
    } else {
      current = current ? current + '\n\n' + para : para;
    }
  }
  if (current.trim()) result.push(current.trim());
  return result;
}

// 由資料夾名（docId）推得 phase：取 NPDS 代碼的階段碼（C560 → C5）。取不到回傳 null。
function phaseFromFolderName(name) {
  const code = extractNpdsCode(name);
  return code ? `C${code[1]}` : null;
}

// 共用：把 rawChunks 批次 embedding 後，先清除該 docId 舊資料再寫入。回傳寫入筆數。
// rawRows（sidecar 表格列）一併 embedding 後寫入 table_rows（store 不支援時靜默略過，
// 如測試注入的簡化 store）；clear 已同步清舊列，順序為 clear → add → addTableRows。
async function embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store, rawRows = []) {
  if (rawChunks.length === 0) {
    await store.clear(docId, projectId);
    return 0;
  }
  const embeddedChunks = [];
  for (let i = 0; i < rawChunks.length; i += EMBED_BATCH_SIZE) {
    const batch = rawChunks.slice(i, i + EMBED_BATCH_SIZE);
    // embedding 輸入含章節路徑 title：標題脈絡參與語意比對（DB 的 content 仍為純內文）
    const embeddings = await adapter.embedBatch(batch.map(c => (c.title ? `${c.title}\n${c.text}` : c.text)));
    batch.forEach((chunk, j) => {
      embeddedChunks.push({ docId, title: chunk.title, text: chunk.text, embedding: embeddings[j], projectId, phase });
    });
  }
  const embeddedRows = [];
  if (rawRows.length && typeof store.addTableRows === 'function') {
    for (let i = 0; i < rawRows.length; i += EMBED_BATCH_SIZE) {
      const batch = rawRows.slice(i, i + EMBED_BATCH_SIZE);
      const embeddings = await adapter.embedBatch(batch.map(r => (r.title ? `${r.title}\n${r.text}` : r.text)));
      batch.forEach((row, j) => {
        embeddedRows.push({ docId, title: row.title, text: row.text, firstCell: row.firstCell, embedding: embeddings[j], projectId });
      });
    }
  }
  await store.clear(docId, projectId);
  await store.add(embeddedChunks);
  if (embeddedRows.length) await store.addTableRows(embeddedRows);
  return embeddedChunks.length;
}

// Web 上傳路徑：單一 md 檔，docId = 檔名。
async function ingestFile(filePath, filename, projectId, phase, llmAdapter, vectorAdapter) {
  const adapter = llmAdapter || llm;
  const store = vectorAdapter || vectorStore;

  const markdownText = fs.readFileSync(filePath, 'utf-8');
  const docId = filename;
  const rawChunks = parseAndChunk(markdownText, filename);
  if (rawChunks.length === 0) return 0;

  const rawRows = extractTableRows(markdownText, filename);
  return embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store, rawRows);
}

// 把資料夾內所有 .md 切塊；每個 chunk 的 title 標示來源 md 檔名。
function chunkFolderMarkdown(folderPath, projectId, docId) {
  const mdFiles = fs.readdirSync(folderPath).filter(f => f.toLowerCase().endsWith('.md')).sort();
  if (mdFiles.length === 0) {
    throw new Error(`資料夾內找不到任何 .md：${folderPath}`);
  }
  const fileIndex = buildFileIndex(folderPath); // 供 Obsidian wiki-link 解析實際子路徑
  const rawChunks = [];
  const rawRows = [];
  for (const mdName of mdFiles) {
    const text = rewriteImageLinks(fs.readFileSync(path.join(folderPath, mdName), 'utf-8'), projectId, docId, fileIndex);
    for (const c of parseAndChunk(text, mdName)) {
      // 來源 md 檔名記進 title，多 md 時可追溯（無標題的塊 title 已是 mdName，不重複加）
      const title = c.title === mdName ? mdName : `${mdName} › ${c.title}`;
      rawChunks.push({ title, text: c.text });
    }
    for (const r of extractTableRows(text, mdName)) {
      const title = r.title.startsWith(mdName) ? r.title : `${mdName} › ${r.title}`;
      rawRows.push({ ...r, title });
    }
  }
  return { rawChunks, rawRows, mdCount: mdFiles.length };
}

// 驗證資料夾頂層恰好一個 PDF（folder 進料的原始檔），回傳該 PDF 檔名；0 或多於一個則丟錯。
function requirePdf(folderPath) {
  const pdfs = fs.readdirSync(folderPath).filter(f => f.toLowerCase().endsWith('.pdf'));
  if (pdfs.length === 0) throw new Error(`資料夾需含一個 PDF 原始檔（供下載）：${folderPath}`);
  if (pdfs.length > 1) throw new Error(`資料夾的 PDF 需恰好一個，找到 ${pdfs.length} 個：${folderPath}`);
  return pdfs[0];
}

// 把整個資料夾原樣複製到持久位置（含 PDF、md、images）；重複進料整夾替換。回傳圖片數。
function persistFolderAssets(folderPath, projectId, docId, docsRoot) {
  const dest = path.join(docsRoot, projectId, docId);
  fs.rmSync(dest, { recursive: true, force: true });
  fs.cpSync(folderPath, dest, { recursive: true });

  const imagesSrc = path.join(folderPath, 'images');
  if (fs.existsSync(imagesSrc) && fs.statSync(imagesSrc).isDirectory()) {
    return fs.readdirSync(imagesSrc).filter(f => fs.statSync(path.join(imagesSrc, f)).isFile()).length;
  }
  return 0;
}

// 資料夾進料路徑：一資料夾 = 一 docId（= 資料夾名），可多 md，共用 images/。
// opts: { projectId, phase, docId?, docsRoot? }
async function ingestFolder(folderPath, opts, llmAdapter, vectorAdapter) {
  const adapter = llmAdapter || llm;
  const store = vectorAdapter || vectorStore;
  const folder = folderPath.replace(/[\\/]+$/, '');
  const projectId = opts.projectId;
  const phase = opts.phase;
  const docId = opts.docId || path.basename(folder);
  const docsRoot = opts.docsRoot || path.join(process.cwd(), 'public', 'documents');

  requirePdf(folder); // 進料前驗證：必含恰好一個 PDF 原始檔（供下載）
  const { rawChunks, rawRows, mdCount } = chunkFolderMarkdown(folder, projectId, docId);
  const chunkCount = await embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store, rawRows);
  const imageCount = persistFolderAssets(folder, projectId, docId, docsRoot);

  return { docId, mdCount, chunkCount, imageCount };
}

module.exports = {
  parseAndChunk,
  extractTableRows,
  ingestFile,
  ingestFolder,
  phaseFromFolderName,
  rewriteImageLinks,
};
