const fs = require('fs');
const path = require('path');
const { marked } = require('marked');
const llm = require('../adapters/llm');
const vectorStore = require('../adapters/vector');
const { extractNpdsCode } = require('../config/npds-catalog');
const { rewriteImageLinks, buildFileIndex } = require('./imageLinks');

const MAX_CHUNK_LENGTH = 1500;
// 批次 embedding 每批筆數，降低 API 請求數與 429 風險
const EMBED_BATCH_SIZE = 100;

// .docx 等格式經 markitdown 轉檔時，若圖片沒有作者手寫的替代文字，Word 會自動產生
// alt-text 並固定帶一句免責聲明，markitdown 原樣保留進 Markdown。含多張圖的 chunk 因此
// 重複出現這句話多次，任何查詢命中這句話裡的詞（如「AI」）時 BM25 詞頻被純噪音灌高，
// 蓋過真正相關但圖少/沒圖的 chunk（實測案例：EAR-100T AI 運算效能那題）。
// 只移除這句固定字串本身，不影響圖片語法或 alt-text 裡其他描述文字。
function stripAutoGeneratedBoilerplate(text) {
  return String(text || '').replace(/\s*AI\s+產生的內容可能不正確[。.]?/g, '');
}

function parseAndChunk(markdownText, filename) {
  const tokens = marked.lexer(stripAutoGeneratedBoilerplate(markdownText));
  const chunks = [];
  // 標題階層堆疊：title 為完整章節路徑（H1 › H2 › H3），深層小節才保得住脈絡，
  // 且路徑會參與 embedding/FTS 比對。無任何標題時 title 為檔名。
  const headingStack = [];
  let currentText = '';

  const currentTitle = () =>
    (headingStack.length ? headingStack.map(h => h.text).join(' › ') : filename);

  function flushChunk() {
    const text = currentText.trim();
    if (text) {
      const title = currentTitle();
      splitLongChunk(text, title).forEach(t => chunks.push({ title, text: t }));
    }
    currentText = '';
  }

  // 「整段皆為粗體」的段落當標題邊界：有些文件（如 FAQ）用 **Q1: ...** 粗體充當段落標題、
  // 完全沒有 # 標題，若不處理會被整份視為無標題、按長度硬切，多個不相關主題混進同一 chunk，
  // 單一主題查詢對這種多主題 chunk 召回被稀釋。深度給 BOLD_HEADING_DEPTH（比任何 # 都深），
  // 附加在現有 # 章節路徑之下、不覆蓋它。只認「整段粗體」，行內部分粗體不算。
  const BOLD_HEADING_DEPTH = 99;
  const boldHeadingText = (token) => {
    if (token.type !== 'paragraph') return null;
    const raw = String(token.raw || '').trim();
    const m = raw.match(/^\*\*([^\n]+?)\*\*$/); // 單行、整行以 ** 包裹
    return m ? m[1].trim() : null;
  };

  for (const token of tokens) {
    const boldTitle = boldHeadingText(token);
    if (token.type === 'heading' || boldTitle) {
      flushChunk();
      const depth = boldTitle ? BOLD_HEADING_DEPTH : token.depth;
      const text = boldTitle || token.text;
      // 同層或較淺的標題出現 → 截斷堆疊再壓入（跳層按實際 depth 放，不補洞）
      while (headingStack.length && headingStack[headingStack.length - 1].depth >= depth) {
        headingStack.pop();
      }
      headingStack.push({ depth, text });
    } else if (token.type === 'space') {
      currentText += '\n';
    } else if (token.raw) {
      currentText += token.raw;
    }
  }
  flushChunk();

  return chunks;
}

function splitLongChunk(text, title) {
  if (text.length <= MAX_CHUNK_LENGTH) return [text];

  const paragraphs = text.split(/\n+/).filter(p => p.trim());
  const result = [];
  let current = '';

  for (const para of paragraphs) {
    if (current.length + para.length + 2 > MAX_CHUNK_LENGTH && current.length > 0) {
      result.push(current.trim());
      current = para;
    } else {
      current = current ? current + '\n\n' + para : para;
    }
  }
  if (current.trim()) result.push(current.trim());
  return result;
}

// 由資料夾名（docId）推得 phase：取 NPDS 代碼的階段碼（C560 → C5）。取不到回傳 null。
function phaseFromFolderName(name) {
  const code = extractNpdsCode(name);
  return code ? `C${code[1]}` : null;
}

// 共用：把 rawChunks 批次 embedding 後，先清除該 docId 舊資料再寫入。回傳寫入筆數。
async function embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store) {
  if (rawChunks.length === 0) {
    await store.clear(docId, projectId);
    return 0;
  }
  const embeddedChunks = [];
  for (let i = 0; i < rawChunks.length; i += EMBED_BATCH_SIZE) {
    const batch = rawChunks.slice(i, i + EMBED_BATCH_SIZE);
    // embedding 輸入含章節路徑 title：標題脈絡參與語意比對（DB 的 content 仍為純內文）
    const embeddings = await adapter.embedBatch(batch.map(c => (c.title ? `${c.title}\n${c.text}` : c.text)));
    batch.forEach((chunk, j) => {
      embeddedChunks.push({ docId, title: chunk.title, text: chunk.text, embedding: embeddings[j], projectId, phase });
    });
  }
  await store.clear(docId, projectId);
  await store.add(embeddedChunks);
  return embeddedChunks.length;
}

// Web 上傳路徑：單一 md 檔，docId = 檔名。
async function ingestFile(filePath, filename, projectId, phase, llmAdapter, vectorAdapter) {
  const adapter = llmAdapter || llm;
  const store = vectorAdapter || vectorStore;

  const markdownText = fs.readFileSync(filePath, 'utf-8');
  const docId = filename;
  const rawChunks = parseAndChunk(markdownText, filename);
  if (rawChunks.length === 0) return 0;

  return embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store);
}

// 把資料夾內所有 .md 切塊；每個 chunk 的 title 標示來源 md 檔名。
function chunkFolderMarkdown(folderPath, projectId, docId) {
  const mdFiles = fs.readdirSync(folderPath).filter(f => f.toLowerCase().endsWith('.md')).sort();
  if (mdFiles.length === 0) {
    throw new Error(`資料夾內找不到任何 .md：${folderPath}`);
  }
  const fileIndex = buildFileIndex(folderPath); // 供 Obsidian wiki-link 解析實際子路徑
  const rawChunks = [];
  for (const mdName of mdFiles) {
    const text = rewriteImageLinks(fs.readFileSync(path.join(folderPath, mdName), 'utf-8'), projectId, docId, fileIndex);
    for (const c of parseAndChunk(text, mdName)) {
      // 來源 md 檔名記進 title，多 md 時可追溯（無標題的塊 title 已是 mdName，不重複加）
      const title = c.title === mdName ? mdName : `${mdName} › ${c.title}`;
      rawChunks.push({ title, text: c.text });
    }
  }
  return { rawChunks, mdCount: mdFiles.length };
}

// 驗證資料夾頂層恰好一個 PDF（folder 進料的原始檔），回傳該 PDF 檔名；0 或多於一個則丟錯。
function requirePdf(folderPath) {
  const pdfs = fs.readdirSync(folderPath).filter(f => f.toLowerCase().endsWith('.pdf'));
  if (pdfs.length === 0) throw new Error(`資料夾需含一個 PDF 原始檔（供下載）：${folderPath}`);
  if (pdfs.length > 1) throw new Error(`資料夾的 PDF 需恰好一個，找到 ${pdfs.length} 個：${folderPath}`);
  return pdfs[0];
}

// 把整個資料夾原樣複製到持久位置（含 PDF、md、images）；重複進料整夾替換。回傳圖片數。
function persistFolderAssets(folderPath, projectId, docId, docsRoot) {
  const dest = path.join(docsRoot, projectId, docId);
  fs.rmSync(dest, { recursive: true, force: true });
  fs.cpSync(folderPath, dest, { recursive: true });

  const imagesSrc = path.join(folderPath, 'images');
  if (fs.existsSync(imagesSrc) && fs.statSync(imagesSrc).isDirectory()) {
    return fs.readdirSync(imagesSrc).filter(f => fs.statSync(path.join(imagesSrc, f)).isFile()).length;
  }
  return 0;
}

// 資料夾進料路徑：一資料夾 = 一 docId（= 資料夾名），可多 md，共用 images/。
// opts: { projectId, phase, docId?, docsRoot? }
async function ingestFolder(folderPath, opts, llmAdapter, vectorAdapter) {
  const adapter = llmAdapter || llm;
  const store = vectorAdapter || vectorStore;
  const folder = folderPath.replace(/[\\/]+$/, '');
  const projectId = opts.projectId;
  const phase = opts.phase;
  const docId = opts.docId || path.basename(folder);
  const docsRoot = opts.docsRoot || path.join(process.cwd(), 'public', 'documents');

  requirePdf(folder); // 進料前驗證：必含恰好一個 PDF 原始檔（供下載）
  const { rawChunks, mdCount } = chunkFolderMarkdown(folder, projectId, docId);
  const chunkCount = await embedAndStore(rawChunks, { docId, projectId, phase }, adapter, store);
  const imageCount = persistFolderAssets(folder, projectId, docId, docsRoot);

  return { docId, mdCount, chunkCount, imageCount };
}

module.exports = {
  parseAndChunk,
  ingestFile,
  ingestFolder,
  phaseFromFolderName,
  rewriteImageLinks,
};
